/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : bigint,
  'memberId' : bigint,
  'method' : string,
  'memberName' : string,
  'timestamp' : bigint,
}
export type CheckInResult = { 'invalidMethod' : null } |
  { 'notFound' : null } |
  { 'duplicate' : null } |
  { 'success' : null };
export interface Member {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'qrToken' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkInByFace' : ActorMethod<[bigint], CheckInResult>,
  'checkInByQR' : ActorMethod<[string], CheckInResult>,
  'createMember' : ActorMethod<[string, string], Member>,
  'getAllAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMemberAttendance' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getMemberByQR' : ActorMethod<[string], [] | [Member]>,
  'getTodaysAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];