/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CheckInResult = IDL.Variant({
  'invalidMethod' : IDL.Null,
  'notFound' : IDL.Null,
  'duplicate' : IDL.Null,
  'success' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'qrToken' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'memberId' : IDL.Nat,
  'method' : IDL.Text,
  'memberName' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkInByFace' : IDL.Func([IDL.Nat], [CheckInResult], []),
  'checkInByQR' : IDL.Func([IDL.Text], [CheckInResult], []),
  'createMember' : IDL.Func([IDL.Text, IDL.Text], [Member], []),
  'getAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMemberAttendance' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getMemberByQR' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
  'getTodaysAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CheckInResult = IDL.Variant({
    'invalidMethod' : IDL.Null,
    'notFound' : IDL.Null,
    'duplicate' : IDL.Null,
    'success' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'qrToken' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'memberId' : IDL.Nat,
    'method' : IDL.Text,
    'memberName' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkInByFace' : IDL.Func([IDL.Nat], [CheckInResult], []),
    'checkInByQR' : IDL.Func([IDL.Text], [CheckInResult], []),
    'createMember' : IDL.Func([IDL.Text, IDL.Text], [Member], []),
    'getAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMemberAttendance' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getMemberByQR' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
    'getTodaysAttendance' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };